# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 01:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_method', models.CharField(choices=[('NONE', '請選擇交換方式'), ('MAIL', '郵寄'), ('FACE', '面交'), ('BOTH', '兩者皆可')], default='NONE', max_length=10)),
                ('city', models.CharField(choices=[('NONE', '請選擇面交城市'), ('KLU', '基隆市'), ('TPE', '台北市'), ('TPH', '新北市'), ('ILN', '宜蘭縣'), ('HSC', '新竹市'), ('HSH', '新竹縣'), ('TYC', '桃園市'), ('MAL', '苗栗縣'), ('TXG', '台中市'), ('CWH', '彰化縣'), ('NTO', '南投縣'), ('CIC', '嘉義市'), ('CIH', '嘉義縣'), ('YUN', '雲林縣'), ('TNN', '台南市'), ('KHH', '高雄市'), ('IUH', '屏東縣'), ('TTT', '台東縣'), ('HWA', '花蓮縣'), ('KMN', '金門縣'), ('LNN', '連家縣'), ('PEH', '澎湖縣')], default='NONE', max_length=5)),
                ('area_description', models.CharField(blank=True, max_length=100)),
                ('contact_description', models.CharField(blank=True, max_length=500)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
