# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20171010_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='book.Book'),
        ),
    ]
