# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 12:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0005_auto_20171010_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='targeted_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='target_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
