# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_exchangeitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangeitem',
            old_name='fromItem',
            new_name='from_item',
        ),
        migrations.RenameField(
            model_name='exchangeitem',
            old_name='fromUser',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='exchangeitem',
            old_name='toItem',
            new_name='to_item',
        ),
        migrations.RenameField(
            model_name='exchangeitem',
            old_name='toUser',
            new_name='to_user',
        ),
    ]
