# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20171017_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeitem',
            name='status',
        ),
        migrations.AddField(
            model_name='exchangeitem',
            name='from_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchangeitem',
            name='to_status',
            field=models.IntegerField(default=0),
        ),
    ]
