# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20171017_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeitem',
            name='from_status',
        ),
        migrations.RemoveField(
            model_name='exchangeitem',
            name='to_status',
        ),
        migrations.AddField(
            model_name='exchangeitem',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
