# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20171018_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
